const pizza=[
    {
        "id": "01",
        "name": "Onion Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "02",
        "name": "Corn Pizza",
        "image": "Corn Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "03",
        "name": "Capsicum Pizza",
        "image": "Capsicum Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "04",
        "name": "Tomato Pizza",
        "image": "Tomato Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "05",
        "name": "Cheese Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "06",
        "name": "Mushroom Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "07",
        "name": "Spicy Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "08",
        "name": "Pineapple Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "09",
        "name": "Paneer Cheese Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "10",
        "name": "Tomato & Capsicum Pizza",
        "image": "Tomato & Capsicum Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "11",
        "name": "Onion & Capsicum Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "12",
        "name": "Jalapeno & Corn Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "13",
        "name": "Onion & Golden Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "14",
        "name": "Healthy Classic Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "15",
        "name": "Paneer & Onion Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "16",
        "name": "Tomato & Cheese Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "17",
        "name": "Spicy Paneer Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "18",
        "name": "Tandoori Paneer Tikka Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "19",
        "name": "Farm Harvested Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "20",
        "name": "Paneer Makhani Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "21",
        "name": "Double Cheese Margherita Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "22",
        "name": "Veggie Crush Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "23",
        "name": "Veggie Paradise Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "24",
        "name": "Spicy Heaven Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "25",
        "name": "Deluxe Delight Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    },
    {
        "id": "26",
        "name": "Express Spicy Pizza",
        "image": "Onion Pizza.jpg",
        "price": ["100","200","300"],
        "size": ["small", "medium", "large"],
    }
]